version: '3.8'

services:
  old_app_1:
    image: nginx:latest
    container_name: old_app_1
    volumes:
      - ./old:/usr/share/nginx/html:ro
    ports:
      - '8081:80'
  old_app_2:
    image: nginx:latest
    container_name: old_app_2
    volumes:
      - ./old:/usr/share/nginx/html:ro
    ports:
      - '8082:80'
  new_app_1:
    image: nginx:latest
    container_name: new_app_1
    volumes:
      - ./new:/usr/share/nginx/html:ro
    ports:
      - '8083:80'
  new_app_2:
    image: nginx:latest
    container_name: new_app_2
    volumes:
      - ./new:/usr/share/nginx/html:ro
    ports:
      - '8084:80'
  load_balancer:
    image: nginx:latest
    container_name: load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8080:80'
